name: CMake

on: [push, pull_request]

jobs:
  build-windows:
    env:
      BUILD_TYPE: Release
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
    strategy:
      fail-fast: false
      matrix:
        include:
        - type: Win32
          triplet: x86-windows-static
          mono: ''
          dll_sfx: windows.i386
        - type: x64
          triplet: x64-windows-static
          mono: ''
          dll_sfx: windows.amd64
          
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build
      
    - name: Cache
      uses: actions/cache@v3
      id: cache
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ${{github.workspace}}\vcpkg\vcpkg.exe
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-${{ matrix.triplet }}-20221125re
        restore-keys:  ${{ runner.os }}-${{ matrix.triplet }}-20221125re

    - name: Setup Vcpkg
      shell: cmd
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/vcpkg
      run: bootstrap-vcpkg.bat
      
    - name: 'Setup NuGet Credentials'
      shell: 'bash'
      # Replace <OWNER> with your organization name
      run: >
        ${{ matrix.mono }} `./vcpkg/vcpkg fetch nuget | tail -n 1`
        sources add
        -source "https://nuget.pkg.github.com/Dice-Developer-Team/index.json"
        -storepasswordincleartext
        -name "GitHub"
        -username "Dice-Developer-Team"
        -password "${{ secrets.GITHUB_TOKEN }}"

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -A ${{ matrix.type }} -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DDLL_SUFFIX=.${{matrix.dll_sfx}} -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE
      
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        # Artifact name
        name: ${{ matrix.triplet }}
        # A file, directory or wildcard pattern that describes what to upload
        path: "**/w4123.Dice.${{ matrix.dll_sfx }}.dll"
